### PR TITLE
Added Chinese (Simplified) (zh-CN) translation

### PR DESCRIPTION
**Pull request by imgradeone**
Still incomplete. Some strings are kept untranslated as I don't certainly know how to translate them,

### CODE REVIEW

**Comment by angelbruni** [comment]
Oh my God, thank you so much!
I will look into this tomorrow, should I wait some more or shoukd I merge as soon as I can?

**Comment by imgradeone** [comment]
I'm fine with merging now, as I still don't have much mind on some strings. Maybe some other people could help.
:(

**Comment by angelbruni** [comment]
Heyyy, it's fine, don't worry!
I will merge tomorrow them, thank you so much, I really appreciate it :D

**Comment by angelbruni** [comment]
Just finished verifying everything, thank you very much!

**Pull request merged**
