### PR TITLE
Fixing and updating tagalog localisation

### PR DESCRIPTION
**Pull request by emeraldsucksss**
This pullrequest updates the tagalog translation, which might have been broken for a while.

### CODE REVIEW

**Review by angelbruni — CHANGES_REQUESTED** [review]
Why are so many of these strings in brackets?

**Comment by emeraldsucksss** [comment]
shii, the brackets were included with the glitched untranslated text, kept them in cause i thought they were needed.

**Comment by angelbruni** [comment]
> shii, the brackets were included with the glitched untranslated text, kept them in cause i thought they were needed.

Every pseudo always had brackets, and the ONE string that has brackets had them removed by you, the `[BUILT-IN] {{themeName}}` one.

fix pls k thx

**Comment by emeraldsucksss** [comment]
Fixed the issues, please review

**Review by angelbruni — CHANGES_REQUESTED** [review]
- You have reverted a lot of strings that were added/changed in recent commits;
- "[BUILT-IN]" was made a part of the theme name in your string ("Firefox Alpenglow" would say "Naka-built in Firefox Alpenglow" instead of "[NAKA-BUILT IN] Firefox Alpenglow" (or whatever is more fitting), in your way, it just looks like "Naka-built in Firefox Alpenglow" is the entire theme name, with a lack of distinction.

**Review by angelbruni — CHANGES_REQUESTED** [review]
Added privacy settings: https://github.com/angelbruni/Geckium/commit/74021c57901648ff3c8af96a804a6dc7e01f998b

**Pull request closed without merging**
