### PR TITLE
Trying to make ru translation

### PR DESCRIPTION
**Pull request by KonaloboStudio**

### CODE REVIEW

**Comment by angelbruni** [comment]
Good morning!
Would you mind telling me if the translations for Chromium strings are straight from Chromium or if they are your own translations? As for Geckium related ones such as GeckiumMaterial, Geckium Wizard and Geckium Settings, they seem to be fine :)

**Comment by KonaloboStudio** [comment]
Some lines (for example, the "about chrome" window) were taken from real chromium. Well, somewhere I had to think of it myself

**Comment by angelbruni** [comment]
I am worried if it's not authentic enough, but something is still better than nothing, and I hope it gives incentive for someone to make it accurate to actual Chromium string.
Or are you wanting to do it? Otherwise I will probably merge this.

**Comment by angelbruni** [comment]
Alright, thank you.
I will review this later and merge if possible.

**Comment by angelbruni** [comment]
By the way, I realised you forgot to change the `customizeAndControlGoogleChrome` string now D:

**Pull request merged**
