### PR TITLE
translate new strings for hr-HR

### PR DESCRIPTION
**Pull request by weeniemount**

### CODE REVIEW

**Comment by Kiki79250CoC** [comment]
You forgot the one at line 78

Also this line is missing at Line 79 :
`<!ENTITY gsettings.enableForceColorizeAddressBarDisclaimer      "Requires Geckium Firefox Theme mode or a compatible Chromium Theme">`

**Comment by weeniemount** [comment]
oops. i translated line 78. also what do you mean mssing at line 79? i dont see anything missing in the original file

**Comment by Kiki79250CoC** [comment]
In the settings, there's `enableForceColorizeAddressBar` and `enableForceColorizeAddressBarDisclaimer`, and your file is missing the latter (as well as others, it's basically an oopsie)

**Comment by angelbruni** [comment]
Updated locales to have the missing string.

**Review by angelbruni — CHANGES_REQUESTED** [review]
Missing string

**Pull request closed without merging**
