### PR TITLE
Update pt-BR

### PR DESCRIPTION
**Pull request by SoftwareType**
### First, I'm gonna warn you that it's, by now, organized just like [this Geckium Canary version](https://github.com/angelbruni/Geckium/actions/runs/11884317271), so it is not quite up-to-date with the source code (that removes the over-exaggerated spaces). In case that's not fine, I'll be able to standardize

image
image

### CODE REVIEW

**Comment by SoftwareType** [comment]
I have just copy pasted from the file in my real computer, so I have no idea why it is conflicting

**Comment by angelbruni** [comment]
> I have just copy pasted from the file in my real computer, so I have no idea why it is conflicting

Looking at "Files Changed" tab, it seems that your file is from before the indentation change from yesterday.
I also had to remove periods at the end of description strings (since Material Design didn't do that either)

**Comment by SoftwareType** [comment]
Oh, makes sense

Gonna fix it later on as I'm gonna be away from the computer for 10 minutes

**Comment by SoftwareType** [comment]
I tried the new code in the Canary update and it appears an error; just checked that ' was used instead of " in one of the titles

Other than that, I have no idea what this means. I suppose but is it actually supposed to happen?
image

**Comment by angelbruni** [comment]
Either way, the file in Canary is also already outdated by now.

**Comment by SoftwareType** [comment]
I think the problem is really about the Canary build being outdated. [After building the latest version (or smth)](https://github.com/SoftwareType/Geekium/actions/runs/11902778231) I have updated the language after an error from [eb7af7d](https://github.com/angelbruni/Geckium/pull/348/commits/eb7af7ddec90456968f6c9c7118ecbae087e5dd8) (for some reason). I have no idea what it changed between the other, but it seems to work now

**Pull request merged**
