### PR TITLE
add hr-HR (Croatian) localization for geckium

### PR DESCRIPTION
**Pull request by weeniemount**
title. adds the Croatian language to the locale folder and adds it to chrome.manifest. also, if there are any inaccuracies, broken stuff, or untranslated strings, please comment about it

### CODE REVIEW

**Comment by angelbruni** [comment]
I will verify this as soon as I can.

At the moment, the credits screen is dedicated to only those who developed and privately tested Geckium, and is not being updated, I only updated it twice to add https://github.com/MrOtherGuy/fx-autoconfig (which loads Geckium) and a private testers which I had forgotten to add (_oops..._).
There's nothing to worry about though, in Geckium releases, in the description it mentions anyone who have contributed to the release and in https://github.com/angelbruni/Geckium/graphs/contributors it shows everyone who contributed and what they contributed with.

**Comment by weeniemount** [comment]
sorry i actually meant to delete the am i allowed to add myself as i changed my mind

**Comment by angelbruni** [comment]
Don't worry, it's good to get clarified about things!

**Comment by angelbruni** [comment]
Thank you very much!

**Pull request merged**
