### PR TITLE
Geckium tagalog translation

### PR DESCRIPTION
**Pull request by emeraldsucksss**
geckium tagalog dub real 1080p HD H.264 

tl-PH

### CODE REVIEW

**Comment by angelbruni** [comment]
Are you going to translate `gsplash.dtd`, `gwizard.dtd`, `neterror.dtd` and `ntp.dtd`?

**Comment by emeraldsucksss** [comment]
> Are you going to translate `gsplash.dtd`, `gwizard.dtd`, `neterror.dtd` and `ntp.dtd`?

I already did? Can you check the tl-PH folder? I'll try to delete and re-upload those files if it didn't go through somehow

**Comment by angelbruni** [comment]
> > Are you going to translate `gsplash.dtd`, `gwizard.dtd`, `neterror.dtd` and `ntp.dtd`?
> 
> I already did? Can you check the tl-PH folder? I'll try to delete and re-upload those files if it didn't go through somehow

You can look here https://github.com/angelbruni/Geckium/pull/253/files#diff-928b6be3b2f85437b793c977952ec786166215fefff7c71aa4d6867167832850 that they are not translated.

**Comment by emeraldsucksss** [comment]
> > > Are you going to translate `gsplash.dtd`, `gwizard.dtd`, `neterror.dtd` and `ntp.dtd`?
> > 
> > 
> > I already did? Can you check the tl-PH folder? I'll try to delete and re-upload those files if it didn't go through somehow
> 
> You can look here https://github.com/angelbruni/Geckium/pull/253/files#diff-928b6be3b2f85437b793c977952ec786166215fefff7c71aa4d6867167832850 and see that they are not translated.

Well, damn. My changes for those files didn't save. I was using Notepad++ to edit them. I'll translate the files right now using a different text editor.

**Comment by angelbruni** [comment]
RIP D:

**Pull request closed without merging**
