### PR TITLE
A translation for Ukrainian

### PR DESCRIPTION
**Pull request by megamanyoutuber**

### CODE REVIEW

**Comment by megamanyoutuber** [comment]
> You didn't yet translate the DTD files - please translate them

Will do that now

**Comment by weeniemount** [comment]
...you gonna do it or?

**Comment by megamanyoutuber** [comment]
> ...you gonna do it or?

Will do it.

**Comment by megamanyoutuber** [comment]
Should be done now.

**Review by weeniemount — APPROVED** [review]
should be good to go

**Comment by angelbruni** [comment]
Thank you!

**Pull request merged**
