### PR TITLE
Update for French locale™: Revenge of the baguette

### PR DESCRIPTION
**Pull request by Kiki79250CoC**
drawingLa traduction, c'est moi !</br></br>
#MakingShitWhenYoureTiredAt7amCuzYouHaventSleptYet

### CODE REVIEW

**Review by angelbruni — CHANGES_REQUESTED** [review]
There was a new string added since then (hopefully the last ones before an update...)

**Review by angelbruni — APPROVED** [review]

**Review by angelbruni — CHANGES_REQUESTED** [review]
Alright added more strings for a long requested feature. Sorry, I just remembered about it last minute.

**Comment by weeniemount** [comment]
🥖

**Comment by angelbruni** [comment]
🥖

**Comment by Kiki79250CoC** [comment]
k

**Comment by angelbruni** [comment]
Thank you!

**Pull request merged**
