### PR TITLE
Updated zh-CN translations

### PR DESCRIPTION
**Pull request by imgradeone**
Still incomplete, but way further.

- Completed more translations, took the best effort to make those new translated strings match original Chrome / Chromium.
- Visually improved some strings (maybe?) to provide a closer experience to Chrome.
- Follow-up translations on recent `gsettings.dtd` strings.

### CODE REVIEW

**Review by angelbruni — CHANGES_REQUESTED** [review]
In `gsettings.dtd` there has been a lot of changes to "People" strings and some more feature additions. Sorry D:

**Review by angelbruni — CHANGES_REQUESTED** [review]
Added privacy settings: https://github.com/angelbruni/Geckium/commit/74021c57901648ff3c8af96a804a6dc7e01f998b

**Comment by imgradeone** [comment]
Pushed translation updates.

**Review by angelbruni — APPROVED** [review]

**Comment by angelbruni** [comment]
Thanks!

**Pull request merged**
